// Starter list of real, well-known Indian higher-education institutions, so
// the college search in profile building isn't empty before real candidate
// submissions build up the pool (see /api/candidate/profile-options). Not
// exhaustive — just enough that common searches return something on day
// one. Grows from real "Other" submissions from here on; this list is
// never re-generated or pruned automatically.
export const SEED_INSTITUTIONS: string[] = [
  // IITs
  "IIT Bombay",
  "IIT Delhi",
  "IIT Kanpur",
  "IIT Kharagpur",
  "IIT Madras",
  "IIT Roorkee",
  "IIT Guwahati",
  "IIT Hyderabad",
  "IIT Indore",
  "IIT BHU Varanasi",
  "IIT Gandhinagar",
  "IIT Ropar",
  "IIT Patna",
  "IIT Bhubaneswar",
  "IIT Mandi",
  "IIT Jodhpur",
  "IIT Tirupati",
  "IIT Palakkad",
  "IIT Dhanbad (ISM)",
  "IIT Bhilai",
  "IIT Goa",
  "IIT Jammu",
  "IIT Dharwad",

  // NITs
  "NIT Trichy",
  "NIT Warangal",
  "NIT Surathkal",
  "NIT Rourkela",
  "NIT Calicut",
  "NIT Durgapur",
  "NIT Allahabad (MNNIT)",
  "NIT Bhopal (MANIT)",
  "NIT Nagpur (VNIT)",
  "NIT Jaipur (MNIT)",
  "NIT Kurukshetra",
  "NIT Silchar",
  "NIT Hamirpur",
  "NIT Jalandhar",
  "NIT Raipur",
  "NIT Agartala",
  "NIT Patna",
  "NIT Srinagar",
  "NIT Delhi",
  "NIT Goa",
  "NIT Manipur",
  "NIT Meghalaya",
  "NIT Mizoram",
  "NIT Nagaland",
  "NIT Puducherry",
  "NIT Sikkim",
  "NIT Uttarakhand",
  "NIT Andhra Pradesh",
  "NIT Arunachal Pradesh",

  // IIITs
  "IIIT Hyderabad",
  "IIIT Bangalore",
  "IIIT Delhi",
  "IIIT Allahabad",
  "IIIT Pune",

  // IIMs
  "IIM Ahmedabad",
  "IIM Bangalore",
  "IIM Calcutta",
  "IIM Lucknow",
  "IIM Indore",
  "IIM Kozhikode",
  "IIM Shillong",
  "IIM Raipur",
  "IIM Ranchi",
  "IIM Rohtak",
  "IIM Udaipur",
  "IIM Kashipur",
  "IIM Nagpur",
  "IIM Trichy",
  "IIM Amritsar",
  "IIM Bodh Gaya",
  "IIM Sambalpur",
  "IIM Sirmaur",
  "IIM Jammu",
  "IIM Visakhapatnam",

  // Science / research
  "IISc Bangalore",
  "IISER Pune",
  "IISER Kolkata",
  "IISER Mohali",
  "IISER Bhopal",
  "IISER Thiruvananthapuram",
  "IISER Berhampur",
  "IISER Tirupati",

  // Central universities
  "University of Delhi",
  "Jawaharlal Nehru University",
  "Banaras Hindu University",
  "Aligarh Muslim University",
  "Jamia Millia Islamia",
  "University of Hyderabad",
  "Jadavpur University",
  "Anna University",
  "Osmania University",
  "Savitribai Phule Pune University",
  "University of Mumbai",
  "University of Calcutta",
  "Panjab University",
  "Visva-Bharati University",
  "Pondicherry University",
  "Andhra University",

  // Major private / deemed universities
  "BITS Pilani",
  "VIT Vellore",
  "SRM Institute of Science and Technology",
  "Manipal Academy of Higher Education",
  "Amity University",
  "Symbiosis International University",
  "Christ University",
  "Ashoka University",
  "Shiv Nadar University",
  "OP Jindal Global University",
  "Thapar Institute of Engineering and Technology",
  "Lovely Professional University",
  "Kalinga Institute of Industrial Technology (KIIT)",

  // Medicine / law / design / management (non-IIM)
  "AIIMS Delhi",
  "Christian Medical College Vellore",
  "JIPMER Puducherry",
  "National Law School of India University (NLSIU) Bangalore",
  "NALSAR University of Law Hyderabad",
  "National Institute of Design (NID) Ahmedabad",
  "XLRI Jamshedpur",
  "Faculty of Management Studies (FMS) Delhi",
  "Indian School of Business (ISB) Hyderabad",
  "MDI Gurgaon",
  "Indian Institute of Foreign Trade (IIFT)",

  // Well-known engineering colleges (non-IIT/NIT)
  "College of Engineering Pune (COEP)",
  "Delhi Technological University (DTU)",
  "Netaji Subhas University of Technology (NSUT)",
  "PSG College of Technology Coimbatore",
  "R.V. College of Engineering Bangalore",
  "BMS College of Engineering Bangalore",
  "M.S. Ramaiah Institute of Technology Bangalore",
  "PEC Chandigarh",
  "Vellore Institute of Technology (VIT) Chennai",
];
