// Starter list of real, widely-used skills across major hiring industries,
// so the skills search in profile building (and job posting) isn't empty
// before real submissions build up the Skill table — same reasoning as
// SEED_INSTITUTIONS in institution-seed.ts (see /api/candidate/profile-options).
// Not exhaustive — broad enough that common searches across tech, office/admin,
// BPO, retail, logistics, finance, healthcare, education, creative, and trade
// roles return something on day one. Grows from real "Other" submissions
// from here on; this list is never re-generated or pruned automatically.
export const SEED_SKILLS: string[] = [
  // Software & IT
  "JavaScript",
  "TypeScript",
  "Python",
  "Java",
  "C",
  "C++",
  "C#",
  "PHP",
  "Ruby",
  "Go",
  "Swift",
  "Kotlin",
  "HTML",
  "CSS",
  "SQL",
  "React",
  "Angular",
  "Vue.js",
  "Node.js",
  "Next.js",
  "Django",
  "Flask",
  "Spring Boot",
  ".NET",
  "REST APIs",
  "GraphQL",
  "Git",
  "Docker",
  "Kubernetes",
  "AWS",
  "Azure",
  "Google Cloud Platform",
  "Linux",
  "Shell Scripting",
  "CI/CD",
  "Software Testing",
  "Manual Testing",
  "Automation Testing",
  "Selenium",
  "QA Testing",
  "Database Management",
  "MySQL",
  "PostgreSQL",
  "MongoDB",
  "Data Structures & Algorithms",
  "Machine Learning",
  "Data Science",
  "Data Analysis",
  "Power BI",
  "Tableau",
  "Excel (Advanced)",
  "Network Administration",
  "System Administration",
  "IT Support",
  "Technical Support",
  "Cybersecurity",
  "Cloud Computing",

  // Office / Administration
  "MS Excel",
  "MS Word",
  "MS PowerPoint",
  "MS Outlook",
  "Google Sheets",
  "Google Docs",
  "Data Entry",
  "Typing",
  "Touch Typing",
  "Office Administration",
  "Front Desk Management",
  "Scheduling",
  "Documentation",
  "Filing & Record Keeping",
  "Email Correspondence",
  "Transcription",
  "Proofreading",
  "Report Writing",

  // Customer Service / BPO
  "Customer Service",
  "Customer Support",
  "Voice Process",
  "Non-Voice Process",
  "Chat Support",
  "Email Support",
  "Call Center Operations",
  "Telecalling",
  "CRM Software",
  "Salesforce",
  "Zendesk",
  "Freshdesk",
  "Complaint Handling",
  "Client Relationship Management",
  "Help Desk Support",

  // Sales & Marketing
  "Sales",
  "Retail Sales",
  "Cold Calling",
  "Lead Generation",
  "Business Development",
  "Account Management",
  "Digital Marketing",
  "Social Media Marketing",
  "SEO",
  "SEM",
  "Email Marketing",
  "Content Writing",
  "Copywriting",
  "Content Marketing",
  "Market Research",
  "Brand Management",
  "Google Ads",
  "Google Analytics",
  "Affiliate Marketing",

  // Retail & E-commerce
  "Inventory Management",
  "Cashiering",
  "Point of Sale (POS) Systems",
  "Merchandising",
  "Stock Management",
  "Order Fulfillment",
  "E-commerce Operations",
  "Visual Merchandising",
  "Store Operations",

  // Logistics & Warehouse
  "Warehouse Management",
  "Supply Chain Management",
  "Inventory Control",
  "Dispatch Coordination",
  "Packing & Labeling",
  "Logistics Coordination",
  "Fleet Management",
  "Procurement",

  // Finance, Banking & Accounting
  "Accounting",
  "Bookkeeping",
  "Tally ERP",
  "QuickBooks",
  "SAP",
  "Financial Analysis",
  "Auditing",
  "Taxation",
  "GST Filing",
  "Payroll Processing",
  "Banking Operations",
  "Loan Processing",
  "Financial Reporting",
  "Budgeting",
  "Invoice Processing",

  // Healthcare
  "Patient Care",
  "Nursing",
  "Medical Billing",
  "Medical Coding",
  "Pharmacy Operations",
  "Phlebotomy",
  "Clinical Documentation",
  "Healthcare Administration",
  "First Aid & CPR",
  "Home Healthcare",

  // Education & Training
  "Teaching",
  "Curriculum Development",
  "Training & Development",
  "Tutoring",
  "Special Education",
  "Classroom Management",
  "E-learning Content Development",
  "Academic Counseling",

  // Creative & Design
  "Graphic Design",
  "UI/UX Design",
  "Adobe Photoshop",
  "Adobe Illustrator",
  "Adobe Premiere Pro",
  "Figma",
  "Canva",
  "Video Editing",
  "Animation",
  "Photography",
  "Content Creation",
  "Illustration",

  // Engineering, Manufacturing & Trades
  "AutoCAD",
  "Mechanical Design",
  "Electrical Wiring",
  "Quality Control",
  "Quality Assurance",
  "Production Planning",
  "CNC Machine Operation",
  "Welding",
  "Plumbing",
  "Carpentry",
  "Equipment Maintenance",
  "Assembly Line Operations",
  "Six Sigma",
  "Lean Manufacturing",

  // HR & Recruitment
  "Recruitment",
  "Talent Acquisition",
  "HR Operations",
  "Payroll Management",
  "Employee Onboarding",
  "Performance Management",
  "HRIS Software",

  // Languages (communication skill, not fluency claim)
  "English Communication",
  "Hindi",
  "Tamil",
  "Telugu",
  "Kannada",
  "Malayalam",
  "Marathi",
  "Bengali",
  "Gujarati",
  "Punjabi",
  "Urdu",
  "Sign Language (ISL)",

  // General / Soft Skills
  "Communication Skills",
  "Teamwork",
  "Problem Solving",
  "Time Management",
  "Leadership",
  "Adaptability",
  "Attention to Detail",
  "Critical Thinking",
  "Project Management",
  "Multitasking",
  "Negotiation",
  "Public Speaking",
  "Conflict Resolution",
];
