-- CreateEnum
CREATE TYPE "AccommodationType" AS ENUM ('SCREEN_READER_SUPPORT', 'SIGN_LANGUAGE_INTERPRETER', 'CAPTIONING', 'WHEELCHAIR_ACCESSIBLE_WORKSPACE', 'ASSISTIVE_TECHNOLOGY_STIPEND', 'FLEXIBLE_HOURS', 'REMOTE_FRIENDLY', 'ERGONOMIC_WORKSTATION', 'ACCESSIBLE_TRANSPORTATION', 'EXTENDED_BREAKS', 'JOB_COACH_SUPPORT', 'OTHER');

-- AlterTable
ALTER TABLE "CandidateProfile" ADD COLUMN     "accommodationNeeds" "AccommodationType"[];

-- AlterTable
ALTER TABLE "Job" ADD COLUMN     "accommodationTypes" "AccommodationType"[];
